[package]
name = "bold_vend_manager_server"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.10.4"
tokio = { version = "1.20.1", features = ["rt-multi-thread"] }
tonic = "0.7.2"

[build-dependencies]
tonic-build = "0.7.2"
