[package]
name = "bold_vend_manager_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.1.0"
futures   = "0.3.21"
prost     = "0.10.4"
tokio     = { version = "1.20.1", features = ["rt-multi-thread"] }
tonic     = "0.7.2"

[build-dependencies]
tonic-build = "0.7.2"
