name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  proto-lint:
    name: Proto Lint
    container: golang:latest
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: |
          cd ./src/proto
          go install github.com/googleapis/api-linter/cmd/api-linter@latest
          go install github.com/golang/protobuf/protoc-gen-go@latest
          api-linter --proto-path=/api-common-protos bolt_vend_api/machine_service.proto bolt_vend_api/manager_service.proto bolt_vend_api/model.proto
